apiVersion: apps/v1
kind: Deployment
metadata: 
  name: echo-server
spec:
  template:
    spec:
      containers:
      - name: hapi
        env:
          - name: ENVIRONMENT
            value: development
