apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  labels:
    app: echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      volumes:
        - name: foo
          configMap:
            name: foo
      containers:
        - name: hapi
          image: darkspark/hapi-test-kubernuts
          envFrom:
            - configMapRef:
                name: with-literals
          volumeMounts:
            - mountPath: /foo
              name: foo


