commonLabels:
  app-group: helloWorld
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
- name: foo
  files: 
  - foo.txt 
- name: with-literals
  literals: 
  - foo=bar
  - other=stuff
